# Generated by Django 3.2.9 on 2021-11-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=128, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=128, verbose_name='e-mail')),
                ('dtnasc', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('L', 'LGBTQIA+')], max_length=12, verbose_name='Sexo')),
                ('estadocivil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('U', 'União Estável'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=12, verbose_name='Estado Civil')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('dtcriacao', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='Quantidade em estoque')),
            ],
        ),
    ]
